checks:
  javascript: true

filter:
  excluded_paths:
    - "build/"
    - "assets/"
    - "test/"
    - "src/javascript"

  dependency_paths:
    - "node_modules/"

build:
  nodes:
    analysis:
      project_setup:
        override: true
        before:
          - make all
      tests:
        override:
          - js-scrutinizer-run

    node6:
      environment:
        node: 6.11.0
      project_setup:
        override: true
        before:
          - npm install -g mocha
      tests:
        override:
          - mocha

    node8:
      environment:
        node: 8.12.0
      project_setup:
        override: true
        before:
          - npm install -g mocha
      tests:
        override:
          - mocha

    node10:
      environment:
        node: 10.12.0
      project_setup:
        override: true
        before:
          - npm install -g mocha
      tests:
        override:
          - mocha

    coverage:
      tests:
        override:
          - command: "./node_modules/.bin/nyc --reporter=clover --reporter=text ./node_modules/mocha/bin/mocha"
            coverage:
              file: "coverage/clover.xml"
              format: "clover"
