checks:
  javascript: true

filter:
  excluded_paths:
    - "build/"
    - "assets/"
    - "test/"
    - "coverage/"

  dependency_paths:
    - "node_modules/"

build:
  nodes:
    analysis:
      project_setup:
        override: true
        before:
          - yarn install
          - make all
      tests:
        override:
          - js-scrutinizer-run
      cache:
        directories:
          - ~/.npm

  tests:
    override:
      - command: "./node_modules/.bin/nyc --reporter=clover --reporter=text ./node_modules/mocha/bin/mocha"
        coverage:
          file: "coverage/clover.xml"
          format: "clover"
