env:
  global:
  - COVERALLS_RUN_LOCALLY=1
  - secure: umegkGPWkYPKh5In5QQ1kgN1b+PH4tzS2xA49qaOUbYIWZZPJEc6SkGnOCOQKZMQuZiQMbK3RmD1INYWV2wNKsjlo1kpXwYJLHSKnO/SbR7teMu4nzs3c5Xr2zMMoV6LMKEm42VXiH4XEvbkLKaGt9fDiiSXTihf6sVZEmPDg8LI9jRK3KjWOEBatL1Wa/9M6ZZYmOwbMKdpRUh8ichVN10YgHby/9BNLa8Jld0Zh3HJyCGbUrvrY/+aTNEe7AWq5J2WXjFHNJXKoun/c9JnPT2weL0hRWChLHyXmaOmzcQsLC/614cSAXbcUbeDTSoRTXmv+Wp0oPYLT1Gq8/NCl7LHXzzluvy1kUZ28qdgHvomLYTN/ZqcRTiqvL7g4qZ3qcpcYBS8yy9OG34M6whlNmNFUlKZkMeqVLGqMjr5/OioYBB57MzVVjceW7kBFedZljzRSaAdZ1sGGQpoAh/RsxsIU6IiI30BdKKKY8hXHm7+N9t77QNwiEJCfn3/87W6DSao+usF2dUYTgdVeKI98jAre59mxqFxUQ3KLMrVL4li1/g+VKoLOk6kUcz8tsDk/BJIz94BNw/P7DtvzVrK/bSSbMkxji80uecPfi0azjTkFRPkhTbSOGKFeV/qCLHYzqfu1UaeA7Xsj7PHhmLqpLk51xXY0QbLEfrlZ3Md/W4=

language: node_js

node_js:
- '6.0'
- '8.0'
- '10.0'

before_script:
- yarn install

cache:
  directories:
  - node_modules

script:
  - npm run test

after_success:
  - travis_retry npm run coverage
