env:
  global:
  - COVERALLS_RUN_LOCALLY=1
  - secure: pLeHhq2RqO8qEAfhY7OHlgfIxuEj414qIviYBpzZ3/nUangjhCvNT2/EfojCeVJaujoWYrM80PmZAk6hIZz6uMUE4ufK536mLB0X1cL/KUBT3gbMGeQrSXrrEJPG1905gFLNNgfOcPygPJo6CkQnd66dYyfi+rmF5pZzKxM9B+u5nzCOnDuU9/EfPltlACGKkPM6qtMCpuuZB34WEpIv52/Gx2rsZXEeh/IlMm/EDOEZsy56MyG9MR3dILMzCwMECR5Ckp765gcv/l2LC6hYB+8RWSu0nqjL5zQi84nAAeyenby789NhnM21Xr1G52K4HwBUbLxkIwE1x/QCPmjbOfTjuANVijFnGee9CVIqcWB/ShOWKzaI8sHmMHOtQML3LYE/lMVqBovmv2tdjK4EuQX3iDYAktug23IpQ/BEJDLwIeivqRqKdJH9yCNjQY4yEtmIRXpw8fVLImHXbGXsqBw3jX7XBFyTZKSrNwCbSFZPw4e7ge9BIzSApX80hl9oq8CS3Zcuj+oEo7KqqKBHttlvvEwcHoplfUZ2279uW2CMl/utF2WEoLCoPM3VjtUXWsHURXM3qm5hAOwwz2gMXgmUQNZQdckf3noj591mPoGqwV6CuFPf5Oah9oneVW2W9XoTDR7txXVR07mr41a/akLgODQn0eincaVA8+jyNlg=

language: node_js

node_js:
  - '6.0'
  - '8.0'
  - '10.0'

before_script:
  - yarn install
cache:
  directories:
    - node_modules

script:
  - npm run test

after_success:
  - travis_retry npm run coverage
