language: node_js

node_js:
  - "6.0"
  - "8.0"
  - "10.0"

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - yarn install

cache:
  directories:
    - node_modules

script:
  - npm run test

after_success:
  - travis_retry npm run coverage

before_deploy:
  - '[[ $(grep "\"version\":" package.json | cut -d\" -f4) != $TRAVIS_TAG ]] && npm version $TRAVIS_TAG || echo "Package versions = tag"'

deploy:
  provider: npm
  email: salaros@yandex.ru
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: CeL45d2tAJD+8TmjBbDznbk5AfKSEwVqqDAwHsHeaDp3/UPBG0OFeD907MWeXkUEjH0lrASE6+c/MDYcYw6vXE/HAD0N30Uy5tDoxuHga+yBiSGwAlIkGcRiA7MBPvP1EYxb16OpHbHf0PqL35UQWKLrKtI07xZQLIn0XS7dCqCdARSnADex+X/tbGCLGNlY/4GxFWK2dsh4FRUglzWQF75FbpqTAP76dEzLraeXOWvaPT3VVISYopHwJa6+8GHROrE3emWdXE1BFZnsx5yeYFIp84NYfFrShcZyYjA30GQMC8Fyk6t1duglK4AZUmzoCxoUhBKh+DTxjBkllfkr6dy7iPMkZahcAb09AIDOUp14qF4JDtj/SN5rtLPUpQvHv1PRQuUf/zjRNdsJLYkhuWYJ9je/J7/TMFX7iM04jzcSX6XNT+aj3j8P2tR1Iud6pu7i9iurJzzU4rCoQB/paQty0qG78dZYqY4CvXgi/ZV/yluwPKtjwedy3CyFpbwpHwEsWIviqb5kNA9AP+e6x6xcZJT1kEhqua8K1tLgvJOLEzhh8PxUZS597EyT6TQ7nQ1Yj2AVGK+UiuRBTMcYXD14OcCMuNYG45iUSdghXoRt62RhjqPFZ3BtfY7x4KJVq4X9xBYg0aI8BZ/GAjMhKUc16SlRR5x1QT0ko7p6u3s=
