language: node_js
node_js:
- '6.0'
- '8.0'
- '10.0'
before_script:
- yarn install
cache:
  directories:
  - node_modules
script:
- npm run test
after_success:
- travis_retry npm run coverage
before_deploy:
- '[[ $(grep "\"version\":" package.json | cut -d\" -f4) != $TRAVIS_TAG ]] && npm version $TRAVIS_TAG || echo "Package versions = tag"'
deploy:
  provider: npm
  email: salaros@yandex.ru
  on:
    tags: true
  api_key:
    secure: SEOtKy+YiEBW6udhS+ddkWodva/gb13N3U40MXHWHdqCMpvZoIN5mWKgJC1JKBlRaopCikejm5nxY/UAvJsU+PfyvSg/GGSU4djkdMMwQxOagjELw3prAvuHHTy9vFYe9JLJzd/v9JvUq/AhHcVoCYV5BaiQ4W7MK/pNd24UwaSf9TfDWd1Pdyqqolpg2hu3waIFjogUhNNKEawGsj0aCFMUi2QBrrdj4pr5+ovORAJF1lVl3jUi7ZfQ3TTWJrSq06MqLFR+jyNARqSqosAPRZV42zVFKVPZUoBzH726aCsADrw6q5CtK6yeoeWf6vgADtMx6ZxLEvt18MuM9hCUCaIYiLR+L3FOPNGLc4CEzB7Z8YpkUu9pKCICI/MuU4qlpgQEBxX1fX3oLrfCWl7SXYc2Brv8O/3vc7TVs5/uzAOC7ZgsJkK4c5wEAWad0uqU8uaMcODStEiTq+Uwo+gDc/SKS/qSwfcnfuj/714By1+5KKM+IFmvwLTneZT4Js/Y2Q4fFjNffTCDEYrcD/EzdldcLsjEBEdgLec4iNKNJoU1anOy+HnmTvLCr7MduwZHQK9QE2TkkkckKp/WTiSULwrxdY0XsLis2SAYau1swU4/xoMs3dPPzNW4NfJLXI535J8asxPO/v7xw9Zd1YcbinrwSpGWH+whtK5d0pVHavA=
